"""Executive impact orchestrator stage (T59).

Subscribed to `remediation.executed` and `risk.forecast.created`. Invokes
the Executive Impact agent, MERGEs into `incident_postmortems` (FR-031/
032), writes Firestore `executive_metrics/latest`, publishes
`executive.metrics.updated`.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[4]))

from agents.common.bq_client import BigQueryClient, param  # noqa: E402
from agents.common.firestore_client import FirestoreClient  # noqa: E402
from agents.common.redaction import redact  # noqa: E402
from agents.executive_impact.agent import (  # noqa: E402
    build_postmortem_merge_params,
    compute_business_impact,
    compute_mttr_reduction,
    compute_resolution_success_rate,
    fetch_linked_customer_accounts,
    merge_postmortem,
)


async def handle_remediation_executed(payload: dict[str, Any]) -> dict[str, Any]:
    incident_id = payload["incidentId"]
    bq_client = BigQueryClient()
    firestore_client = FirestoreClient()

    accounts = fetch_linked_customer_accounts(bq_client, incident_id)
    duration_hours = _incident_duration_hours(bq_client, incident_id)
    impact = compute_business_impact(accounts, incident_duration_hours=duration_hours)
    mttr = compute_mttr_reduction(bq_client)
    success_rate = compute_resolution_success_rate(bq_client)

    # Mark resolved and merge the postmortem only once the remediation
    # outcome (this event) is known -- FR-031 triggers "once per
    # incidents.resolved", which this handler treats as synonymous with a
    # successful remediation.executed for the demo's linear flow.
    bq_client.query(
        """
        UPDATE `sre_incident_mart.incidents`
        SET status = @status, resolved_at = CURRENT_TIMESTAMP()
        WHERE incident_id = @incident_id
        """,
        [param("status", "STRING", "Resolved"), param("incident_id", "STRING", incident_id)],
    )

    postmortem_params = build_postmortem_merge_params(
        incident_id=incident_id,
        root_cause_summary=redact(payload["payload"].get("detail", "See incident record for root cause.")),
        timeline_summary="See /incidents/{id}/timeline for the full correlated-alert timeline.",
        remediation_summary=redact(
            f"Executed action {payload['payload'].get('actionId')}: {payload['payload'].get('detail', '')}"
        ),
        business_impact_summary=(
            f"{impact['affectedCustomers']} customers, {impact['affectedUsers']} users, "
            f"${impact['revenueAtRisk']} revenue at risk, ${impact['slaCreditExposure']} SLA credit exposure."
        ),
        full_report_markdown=redact(f"# Postmortem: {incident_id}\n\nAuto-generated by the Executive Impact Agent."),
        downtime_minutes=round(duration_hours * 60, 1),
    )
    merge_postmortem(bq_client, postmortem_params)

    executive_metrics = {**impact, **mttr, **success_rate, "lastIncidentId": incident_id}
    firestore_client.write_executive_metrics(executive_metrics)

    return {"incidentId": incident_id, "payload": executive_metrics}


async def handle_risk_forecast_created(_payload: dict[str, Any]) -> None:
    """risk.forecast.created only refreshes the executive metrics snapshot's
    predicted-incident count; it never triggers a postmortem (FR-031 is
    resolved-incident-only)."""
    bq_client = BigQueryClient()
    firestore_client = FirestoreClient()
    predictions = firestore_client.list_active_predictions()
    current = firestore_client.get_executive_metrics() or {}
    firestore_client.write_executive_metrics({**current, "predictedIncidentCount": len(predictions)})


def _incident_duration_hours(bq_client: BigQueryClient, incident_id: str) -> float:
    rows = bq_client.query_json_rows(
        """
        SELECT TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), started_at, MINUTE) / 60.0 AS duration_hours
        FROM `sre_incident_mart.incidents`
        WHERE incident_id = @incident_id
        """,
        [param("incident_id", "STRING", incident_id)],
    )
    return (rows[0].get("duration_hours") if rows else None) or 1.0
